### ISSUE TITLE
rename broccoli.png to Broccoli.png

### ISSUE THREAD

**Issue by aaronnhan** [sophie006liu/vegetal#1]
my friend shared this website with me and the result never loaded for me. I inspected the network calls and it gets a 404 when trying to load "Broccoli.png". We should probably change the file to "Broccoli.png" to match the capitalized format of other vegetables.

**Comment by sophie006liu** [comment]
Thank you so much!!! I fixed it :) I hope you can enjoy the quiz normally now!
