### ISSUE TITLE
Typo 2x "must be" 

### ISSUE THREAD

**Issue by coren-frankel** [sophie006liu/vegetal#2]
Saw this typo and wanted to share: "[...] must be must be [...]"
![Screenshot_20240806-134014.png](https://github.com/user-attachments/assets/d126401d-90bf-46e9-bcc1-3d779c273d1d)

Love to be vegetal!

**Comment by sophie006liu** [comment]
Thank you for pointing this out! Just fixed it 

Have a nice day :)
